// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJjDQpvft2JDACtM8T4RRAWdUUjoFgX8',
    appId: '1:44374432443:android:2da2fc1d0f6646d2ae279e',
    messagingSenderId: '44374432443',
    projectId: 'friendge-ad89a',
    storageBucket: 'friendge-ad89a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBclR2BVryGP5UijQPnlogHxe1ruXf_FY8',
    appId: '1:44374432443:ios:0c7be808299096aaae279e',
    messagingSenderId: '44374432443',
    projectId: 'friendge-ad89a',
    storageBucket: 'friendge-ad89a.firebasestorage.app',
    androidClientId: '44374432443-koip4h18cudsvkafpmoujujbanno0ebb.apps.googleusercontent.com',
    iosClientId: '44374432443-rl1mgepr4m130htg5l78j8nejenbi9fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gFridge',
  );

}